version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python app.py"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: flask-backend-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5433:5432"
